[package]
name = "json2file"
authors = ["Tonye Jack <jtonye@ymail.com>"]
version = "0.1.0"
description = "Generate file output from JSON"
readme = "README.md"
license = "MIT"
edition = "2021"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
serde_json = "1.0.91"